// =============================================================================
// vanilla_blocks.js —— 由 tools/gen_vanilla_blocks.py 从 Mindustry v159.7
//   Blocks.java 自动生成，请勿手改；复跑：
//   python3 tools/gen_vanilla_blocks.py <Blocks.java>
//
// 字段：方块内部名 -> { type: 官方 Java 类名, size: 占地, range?: 连接范围 }
// 未标注 size 的方块默认 1；类型是 render_rules.js 类型规则表的键。
// =============================================================================
export const VANILLA_BLOCKS = {
  "additive-reconstructor": { type: "Reconstructor", size: 3 },
  "advanced-launch-pad": { type: "LaunchPad", size: 4 },
  "afflict": { type: "PowerTurret", size: 4, range: 368 },
  "air": { type: "AirBlock", size: 1 },
  "air-factory": { type: "UnitFactory", size: 3 },
  "arc": { type: "PowerTurret", size: 1, range: 90 },
  "arkycite-floor": { type: "Floor", size: 1 },
  "arkyic-boulder": { type: "Prop", size: 1 },
  "arkyic-stone": { type: "Floor", size: 1 },
  "arkyic-vent": { type: "SteamVent", size: 1 },
  "arkyic-wall": { type: "StaticWall", size: 1 },
  "armored-conveyor": { type: "ArmoredConveyor", size: 1 },
  "armored-duct": { type: "Duct", size: 1 },
  "atmospheric-concentrator": { type: "HeatCrafter", size: 3 },
  "basalt": { type: "Floor", size: 1 },
  "basalt-boulder": { type: "StaticProp", size: 1 },
  "basalt-vent": { type: "SteamVent", size: 1 },
  "basic-assembler-module": { type: "UnitAssemblerModule", size: 5 },
  "battery": { type: "Battery", size: 1 },
  "battery-large": { type: "Battery", size: 3 },
  "beam-link": { type: "LongPowerNode", size: 3 },
  "beam-node": { type: "BeamNode", size: 1, range: 10 },
  "beam-tower": { type: "BeamNode", size: 3, range: 23 },
  "beryllic-boulder": { type: "StaticProp", size: 1 },
  "beryllic-stone": { type: "Floor", size: 1 },
  "beryllic-stone-wall": { type: "StaticWall", size: 1 },
  "beryllium-wall": { type: "Wall", size: 1 },
  "beryllium-wall-large": { type: "Wall", size: 2 },
  "blast-door": { type: "AutoDoor", size: 2 },
  "blast-drill": { type: "Drill", size: 4 },
  "blast-mixer": { type: "GenericCrafter", size: 2 },
  "bluemat": { type: "Floor", size: 1 },
  "boulder": { type: "StaticProp", size: 1 },
  "breach": { type: "ItemTurret", size: 3, range: 190 },
  "bridge-conduit": { type: "LiquidBridge", size: 1, range: 4 },
  "bridge-conveyor": { type: "BufferedItemBridge", size: 1, range: 4 },
  "build-tower": { type: "BuildTurret", size: 3, range: 200 },
  "canvas": { type: "CanvasBlock", size: 2 },
  "carbide-crucible": { type: "HeatCrafter", size: 3 },
  "carbide-wall": { type: "Wall", size: 1 },
  "carbide-wall-large": { type: "Wall", size: 2 },
  "carbon-boulder": { type: "StaticProp", size: 1 },
  "carbon-stone": { type: "Floor", size: 1 },
  "carbon-vent": { type: "SteamVent", size: 1 },
  "carbon-wall": { type: "StaticWall", size: 1 },
  "char": { type: "Floor", size: 1 },
  "character-overlay": { type: "CharacterOverlay", size: 1 },
  "character-overlay-white": { type: "CharacterOverlay", size: 1 },
  "chemical-combustion-chamber": { type: "ConsumeGenerator", size: 3 },
  "cliff": { type: "Cliff", size: 1 },
  "cliff-crusher": { type: "WallCrafter", size: 2 },
  "coal-centrifuge": { type: "GenericCrafter", size: 2 },
  "colored-floor": { type: "ColoredFloor", size: 1 },
  "colored-wall": { type: "ColoredWall", size: 1 },
  "combustion-generator": { type: "ConsumeGenerator", size: 1 },
  "command-center": { type: "LegacyCommandCenter", size: 2 },
  "conduit": { type: "Conduit", size: 1 },
  "constructor": { type: "Constructor", size: 3 },
  "container": { type: "StorageBlock", size: 2 },
  "conveyor": { type: "Conveyor", size: 1 },
  "copper-wall": { type: "Wall", size: 1 },
  "copper-wall-large": { type: "Wall", size: 2 },
  "core-acropolis": { type: "CoreBlock", size: 6 },
  "core-bastion": { type: "CoreBlock", size: 4 },
  "core-citadel": { type: "CoreBlock", size: 5 },
  "core-foundation": { type: "CoreBlock", size: 4 },
  "core-nucleus": { type: "CoreBlock", size: 5 },
  "core-shard": { type: "CoreBlock", size: 3 },
  "core-zone": { type: "Floor", size: 1 },
  "crater-stone": { type: "Floor", size: 1 },
  "cryofluid-mixer": { type: "GenericCrafter", size: 2 },
  "crystal-blocks": { type: "TallBlock", size: 1 },
  "crystal-cluster": { type: "TallBlock", size: 1 },
  "crystal-floor": { type: "Floor", size: 1 },
  "crystal-orbs": { type: "TallBlock", size: 1 },
  "crystalline-boulder": { type: "StaticProp", size: 1 },
  "crystalline-stone": { type: "Floor", size: 1 },
  "crystalline-stone-wall": { type: "StaticWall", size: 1 },
  "crystalline-vent": { type: "SteamVent", size: 1 },
  "cultivator": { type: "AttributeCrafter", size: 2 },
  "cyanogen-synthesizer": { type: "HeatCrafter", size: 3 },
  "cyclone": { type: "ItemTurret", size: 3, range: 200 },
  "dacite": { type: "Floor", size: 1 },
  "dacite-boulder": { type: "StaticProp", size: 1 },
  "dacite-wall": { type: "StaticWall", size: 1 },
  "dark-metal": { type: "StaticWall", size: 1 },
  "darksand": { type: "Floor", size: 1 },
  "darksand-tainted-water": { type: "ShallowLiquid", size: 1 },
  "darksand-water": { type: "ShallowLiquid", size: 1 },
  "deconstructor": { type: "PayloadDeconstructor", size: 5 },
  "deep-tainted-water": { type: "Floor", size: 1 },
  "deep-water": { type: "Floor", size: 1 },
  "dense-red-stone": { type: "Floor", size: 1 },
  "differential-generator": { type: "ConsumeGenerator", size: 3 },
  "diffuse": { type: "ItemTurret", size: 3, range: 125 },
  "diode": { type: "PowerDiode", size: 1 },
  "dirt": { type: "Floor", size: 1 },
  "dirt-wall": { type: "StaticWall", size: 1 },
  "disassembler": { type: "Separator", size: 3 },
  "disperse": { type: "ItemTurret", size: 4, range: 310 },
  "distributor": { type: "Router", size: 2 },
  "door": { type: "Door", size: 1 },
  "door-large": { type: "Door", size: 2 },
  "duct": { type: "Duct", size: 1 },
  "duct-bridge": { type: "DuctBridge", size: 1 },
  "duct-router": { type: "DuctRouter", size: 1 },
  "duct-unloader": { type: "DirectionalUnloader", size: 1 },
  "dune-wall": { type: "StaticWall", size: 1 },
  "duo": { type: "ItemTurret", size: 1, range: 160 },
  "electric-heater": { type: "HeatProducer", size: 2 },
  "electrolyzer": { type: "GenericCrafter", size: 3 },
  "empty": { type: "EmptyFloor", size: 1 },
  "eruption-drill": { type: "BurstDrill", size: 5 },
  "exponential-reconstructor": { type: "Reconstructor", size: 7 },
  "ferric-boulder": { type: "StaticProp", size: 1 },
  "ferric-craters": { type: "Floor", size: 1 },
  "ferric-stone": { type: "Floor", size: 1 },
  "ferric-stone-wall": { type: "StaticWall", size: 1 },
  "flux-reactor": { type: "VariableReactor", size: 5 },
  "force-projector": { type: "ForceProjector", size: 3 },
  "foreshadow": { type: "ItemTurret", size: 4, range: 500 },
  "fuse": { type: "ItemTurret", size: 3, range: 90 },
  "graphite-press": { type: "GenericCrafter", size: 2 },
  "graphitic-wall": { type: "StaticWall", size: 1 },
  "grass": { type: "Floor", size: 1 },
  "ground-factory": { type: "UnitFactory", size: 3 },
  "hail": { type: "ItemTurret", size: 1, range: 235 },
  "heat-reactor": { type: "HeatProducer", size: 3 },
  "heat-redirector": { type: "HeatConductor", size: 3 },
  "heat-router": { type: "HeatConductor", size: 3 },
  "heat-source": { type: "HeatProducer", size: 1 },
  "hotrock": { type: "Floor", size: 1 },
  "hyper-processor": { type: "LogicBlock", size: 3, range: 8 },
  "ice": { type: "Floor", size: 1 },
  "ice-snow": { type: "Floor", size: 1 },
  "ice-wall": { type: "StaticWall", size: 1 },
  "illuminator": { type: "LightBlock", size: 1 },
  "impact-drill": { type: "BurstDrill", size: 4 },
  "impact-reactor": { type: "ImpactReactor", size: 4 },
  "impulse-pump": { type: "Pump", size: 3 },
  "incinerator": { type: "Incinerator", size: 1 },
  "interplanetary-accelerator": { type: "Accelerator", size: 7 },
  "inverted-sorter": { type: "Sorter", size: 1 },
  "item-source": { type: "ItemSource", size: 1 },
  "item-void": { type: "ItemVoid", size: 1 },
  "junction": { type: "Junction", size: 1 },
  "kiln": { type: "GenericCrafter", size: 2 },
  "lancer": { type: "PowerTurret", size: 2, range: 165 },
  "landing-pad": { type: "LandingPad", size: 4 },
  "large-canvas": { type: "CanvasBlock", size: 3 },
  "large-cliff-crusher": { type: "WallCrafter", size: 3 },
  "large-constructor": { type: "Constructor", size: 5 },
  "large-logic-display": { type: "LogicDisplay", size: 6 },
  "large-payload-mass-driver": { type: "PayloadMassDriver", size: 5, range: 2100 },
  "large-plasma-bore": { type: "BeamDrill", size: 3, range: 6 },
  "large-shield-projector": { type: "BaseShield", size: 4 },
  "laser-drill": { type: "Drill", size: 3 },
  "launch-pad": { type: "LaunchPad", size: 3 },
  "legacy-mech-pad": { type: "LegacyMechPad", size: 1 },
  "legacy-unit-factory": { type: "LegacyUnitFactory", size: 1 },
  "legacy-unit-factory-air": { type: "LegacyUnitFactory", size: 1 },
  "legacy-unit-factory-ground": { type: "LegacyUnitFactory", size: 1 },
  "liquid-container": { type: "LiquidRouter", size: 2 },
  "liquid-junction": { type: "LiquidJunction", size: 1 },
  "liquid-router": { type: "LiquidRouter", size: 1 },
  "liquid-source": { type: "LiquidSource", size: 1 },
  "liquid-tank": { type: "LiquidRouter", size: 3 },
  "liquid-void": { type: "LiquidVoid", size: 1 },
  "logic-display": { type: "LogicDisplay", size: 3 },
  "logic-processor": { type: "LogicBlock", size: 2, range: 8 },
  "lustre": { type: "ContinuousTurret", size: 4, range: 250 },
  "magmarock": { type: "Floor", size: 1 },
  "malign": { type: "PowerTurret", size: 5, range: 410 },
  "mass-driver": { type: "MassDriver", size: 3, range: 440 },
  "mech-assembler": { type: "UnitAssembler", size: 5 },
  "mech-fabricator": { type: "UnitFactory", size: 3 },
  "mech-refabricator": { type: "Reconstructor", size: 3 },
  "mechanical-drill": { type: "Drill", size: 2 },
  "mechanical-pump": { type: "Pump", size: 1 },
  "meltdown": { type: "LaserTurret", size: 4, range: 195 },
  "melter": { type: "GenericCrafter", size: 1 },
  "memory-bank": { type: "MemoryBlock", size: 2 },
  "memory-cell": { type: "MemoryBlock", size: 1 },
  "mend-projector": { type: "MendProjector", size: 2, range: 85 },
  "mender": { type: "MendProjector", size: 1, range: 40 },
  "message": { type: "MessageBlock", size: 1 },
  "metal-tiles-1": { type: "Floor", size: 1 },
  "metal-tiles-10": { type: "Floor", size: 1 },
  "metal-tiles-11": { type: "Floor", size: 1 },
  "metal-tiles-12": { type: "Floor", size: 1 },
  "metal-tiles-13": { type: "Floor", size: 1 },
  "metal-tiles-2": { type: "Floor", size: 1 },
  "metal-tiles-3": { type: "Floor", size: 1 },
  "metal-tiles-4": { type: "Floor", size: 1 },
  "metal-tiles-5": { type: "Floor", size: 1 },
  "metal-tiles-6": { type: "Floor", size: 1 },
  "metal-tiles-7": { type: "Floor", size: 1 },
  "metal-tiles-8": { type: "Floor", size: 1 },
  "metal-tiles-9": { type: "Floor", size: 1 },
  "metal-wall-1": { type: "StaticWall", size: 1 },
  "metal-wall-2": { type: "StaticWall", size: 1 },
  "metal-wall-3": { type: "StaticWall", size: 1 },
  "micro-processor": { type: "LogicBlock", size: 1 },
  "molten-slag": { type: "Floor", size: 1 },
  "moss": { type: "Floor", size: 1 },
  "mud": { type: "Floor", size: 1 },
  "multi-press": { type: "GenericCrafter", size: 3 },
  "multiplicative-reconstructor": { type: "Reconstructor", size: 5 },
  "naval-factory": { type: "UnitFactory", size: 3 },
  "neoplasia-reactor": { type: "HeaterGenerator", size: 5, range: 4 },
  "oil-extractor": { type: "Fracker", size: 3 },
  "overdrive-dome": { type: "OverdriveProjector", size: 3, range: 200 },
  "overdrive-projector": { type: "OverdriveProjector", size: 2 },
  "overflow-duct": { type: "OverflowDuct", size: 1 },
  "overflow-gate": { type: "OverflowGate", size: 1 },
  "oxidation-chamber": { type: "HeatProducer", size: 3 },
  "parallax": { type: "TractorBeamTurret", size: 2, range: 300 },
  "payload-conveyor": { type: "PayloadConveyor", size: 1 },
  "payload-loader": { type: "PayloadLoader", size: 3 },
  "payload-mass-driver": { type: "PayloadMassDriver", size: 3, range: 700 },
  "payload-router": { type: "PayloadRouter", size: 1 },
  "payload-source": { type: "PayloadSource", size: 5 },
  "payload-unloader": { type: "PayloadUnloader", size: 3 },
  "payload-void": { type: "PayloadVoid", size: 5 },
  "pebbles": { type: "OverlayFloor", size: 1 },
  "phase-conduit": { type: "LiquidBridge", size: 1, range: 12 },
  "phase-conveyor": { type: "ItemBridge", size: 1, range: 12 },
  "phase-heater": { type: "HeatProducer", size: 2 },
  "phase-synthesizer": { type: "HeatCrafter", size: 3 },
  "phase-wall": { type: "Wall", size: 1 },
  "phase-wall-large": { type: "Wall", size: 2 },
  "phase-weaver": { type: "GenericCrafter", size: 2 },
  "pine": { type: "StaticTree", size: 1 },
  "plasma-bore": { type: "BeamDrill", size: 2, range: 5 },
  "plastanium-compressor": { type: "GenericCrafter", size: 2 },
  "plastanium-conveyor": { type: "StackConveyor", size: 1 },
  "plastanium-wall": { type: "Wall", size: 1 },
  "plastanium-wall-large": { type: "Wall", size: 2 },
  "plated-conduit": { type: "ArmoredConduit", size: 1 },
  "pneumatic-drill": { type: "Drill", size: 2 },
  "pooled-cryofluid": { type: "Floor", size: 1 },
  "power-node": { type: "PowerNode", size: 1 },
  "power-node-large": { type: "PowerNode", size: 2 },
  "power-source": { type: "PowerSource", size: 1 },
  "power-void": { type: "PowerVoid", size: 1 },
  "prime-refabricator": { type: "Reconstructor", size: 5 },
  "pulse-conduit": { type: "Conduit", size: 1 },
  "pulverizer": { type: "GenericCrafter", size: 1 },
  "pur-bush": { type: "SeaBush", size: 1 },
  "pyratite-mixer": { type: "GenericCrafter", size: 2 },
  "pyrolysis-generator": { type: "ConsumeGenerator", size: 3 },
  "radar": { type: "Radar", size: 1 },
  "red-diamond-wall": { type: "StaticTree", size: 1 },
  "red-ice": { type: "Floor", size: 1 },
  "red-ice-boulder": { type: "StaticProp", size: 1 },
  "red-ice-wall": { type: "StaticWall", size: 1 },
  "red-stone": { type: "Floor", size: 1 },
  "red-stone-boulder": { type: "StaticProp", size: 1 },
  "red-stone-vent": { type: "SteamVent", size: 1 },
  "red-stone-wall": { type: "StaticWall", size: 1 },
  "redmat": { type: "Floor", size: 1 },
  "redweed": { type: "Seaweed", size: 1 },
  "regen-projector": { type: "RegenProjector", size: 3, range: 28 },
  "regolith": { type: "Floor", size: 1 },
  "regolith-wall": { type: "StaticWall", size: 1 },
  "reinforced-": { type: "DrawTurret", size: 1 },
  "reinforced-bridge-conduit": { type: "DirectionLiquidBridge", size: 1, range: 4 },
  "reinforced-conduit": { type: "ArmoredConduit", size: 1 },
  "reinforced-container": { type: "StorageBlock", size: 2 },
  "reinforced-liquid-container": { type: "LiquidRouter", size: 2 },
  "reinforced-liquid-junction": { type: "LiquidJunction", size: 1 },
  "reinforced-liquid-router": { type: "LiquidRouter", size: 1 },
  "reinforced-liquid-tank": { type: "LiquidRouter", size: 3 },
  "reinforced-message": { type: "MessageBlock", size: 1 },
  "reinforced-payload-conveyor": { type: "PayloadConveyor", size: 1 },
  "reinforced-payload-router": { type: "PayloadRouter", size: 1 },
  "reinforced-pump": { type: "Pump", size: 2 },
  "reinforced-surge-wall": { type: "Wall", size: 1 },
  "reinforced-surge-wall-large": { type: "Wall", size: 2 },
  "reinforced-vault": { type: "StorageBlock", size: 3 },
  "remove-ore": { type: "RemoveOre", size: 1 },
  "remove-wall": { type: "RemoveWall", size: 1 },
  "repair-point": { type: "RepairTurret", size: 1 },
  "repair-turret": { type: "RepairTurret", size: 2 },
  "rhyolite": { type: "Floor", size: 1 },
  "rhyolite-boulder": { type: "StaticProp", size: 1 },
  "rhyolite-crater": { type: "Floor", size: 1 },
  "rhyolite-vent": { type: "SteamVent", size: 1 },
  "rhyolite-wall": { type: "StaticWall", size: 1 },
  "ripple": { type: "ItemTurret", size: 3, range: 290 },
  "rotary-pump": { type: "Pump", size: 2 },
  "rough-rhyolite": { type: "Floor", size: 1 },
  "router": { type: "Router", size: 1 },
  "rtg-generator": { type: "ConsumeGenerator", size: 2 },
  "rune-overlay": { type: "RuneOverlay", size: 1 },
  "rune-overlay-crux": { type: "RuneOverlay", size: 1 },
  "salt": { type: "Floor", size: 1 },
  "salt-wall": { type: "StaticWall", size: 1 },
  "salvo": { type: "ItemTurret", size: 2, range: 190 },
  "sand-boulder": { type: "StaticProp", size: 1 },
  "sand-floor": { type: "Floor", size: 1 },
  "sand-wall": { type: "StaticWall", size: 1 },
  "sand-water": { type: "ShallowLiquid", size: 1 },
  "scathe": { type: "ItemTurret", size: 4, range: 1350 },
  "scathe-missile": { type: "MissileUnitType", size: 1 },
  "scathe-missile-phase": { type: "MissileUnitType", size: 1 },
  "scathe-missile-surge": { type: "MissileUnitType", size: 1 },
  "scathe-missile-surge-split": { type: "MissileUnitType", size: 1 },
  "scatter": { type: "ItemTurret", size: 2, range: 220 },
  "scorch": { type: "ItemTurret", size: 1, range: 60 },
  "scrap-wall": { type: "Wall", size: 1 },
  "scrap-wall-gigantic": { type: "Wall", size: 4 },
  "scrap-wall-huge": { type: "Wall", size: 3 },
  "scrap-wall-large": { type: "Wall", size: 2 },
  "segment": { type: "PointDefenseTurret", size: 2, range: 180 },
  "separator": { type: "Separator", size: 2 },
  "shale": { type: "Floor", size: 1 },
  "shale-boulder": { type: "StaticProp", size: 1 },
  "shale-wall": { type: "StaticWall", size: 1 },
  "shallow-water": { type: "Floor", size: 1 },
  "shield-projector": { type: "BaseShield", size: 3 },
  "shielded-wall": { type: "ShieldWall", size: 2 },
  "ship-assembler": { type: "UnitAssembler", size: 5 },
  "ship-fabricator": { type: "UnitFactory", size: 3 },
  "ship-refabricator": { type: "Reconstructor", size: 3 },
  "shock-mine": { type: "ShockMine", size: 1 },
  "shockwave-tower": { type: "ShockwaveTower", size: 3, range: 170 },
  "shrubs": { type: "StaticWall", size: 1 },
  "silicon-arc-furnace": { type: "GenericCrafter", size: 3 },
  "silicon-crucible": { type: "AttributeCrafter", size: 3 },
  "silicon-smelter": { type: "GenericCrafter", size: 2 },
  "slag-centrifuge": { type: "GenericCrafter", size: 3 },
  "slag-heater": { type: "HeatProducer", size: 3 },
  "slag-incinerator": { type: "ItemIncinerator", size: 1 },
  "small-deconstructor": { type: "PayloadDeconstructor", size: 3 },
  "small-heat-redirector": { type: "HeatConductor", size: 2 },
  "smite": { type: "ItemTurret", size: 5, range: 300 },
  "snow": { type: "Floor", size: 1 },
  "snow-boulder": { type: "StaticProp", size: 1 },
  "snow-pine": { type: "StaticTree", size: 1 },
  "snow-wall": { type: "StaticWall", size: 1 },
  "solar-panel": { type: "SolarGenerator", size: 1 },
  "solar-panel-large": { type: "SolarGenerator", size: 3 },
  "sorter": { type: "Sorter", size: 1 },
  "space": { type: "Floor", size: 1 },
  "spawn": { type: "SpawnBlock", size: 1 },
  "spectre": { type: "ItemTurret", size: 4, range: 260 },
  "spore-cluster": { type: "Prop", size: 1 },
  "spore-moss": { type: "Floor", size: 1 },
  "spore-pine": { type: "StaticTree", size: 1 },
  "spore-press": { type: "GenericCrafter", size: 2 },
  "spore-wall": { type: "StaticWall", size: 1 },
  "steam-generator": { type: "ConsumeGenerator", size: 2 },
  "stone": { type: "Floor", size: 1 },
  "stone-vent": { type: "SteamVent", size: 1 },
  "stone-wall": { type: "StaticWall", size: 1 },
  "sublimate": { type: "ContinuousLiquidTurret", size: 3, range: 130 },
  "surge-conveyor": { type: "StackConveyor", size: 1 },
  "surge-crucible": { type: "HeatCrafter", size: 3 },
  "surge-router": { type: "StackRouter", size: 1 },
  "surge-smelter": { type: "GenericCrafter", size: 3 },
  "surge-tower": { type: "PowerNode", size: 2 },
  "surge-wall": { type: "Wall", size: 1 },
  "surge-wall-large": { type: "Wall", size: 2 },
  "swarmer": { type: "ItemTurret", size: 2, range: 240 },
  "switch": { type: "SwitchBlock", size: 1 },
  "tainted-water": { type: "Floor", size: 1 },
  "tank-assembler": { type: "UnitAssembler", size: 5 },
  "tank-fabricator": { type: "UnitFactory", size: 3 },
  "tank-refabricator": { type: "Reconstructor", size: 3 },
  "tar": { type: "Floor", size: 1 },
  "tendrils": { type: "OverlayFloor", size: 1 },
  "tetrative-reconstructor": { type: "Reconstructor", size: 9 },
  "thermal-generator": { type: "ThermalGenerator", size: 2 },
  "thorium-reactor": { type: "NuclearReactor", size: 3 },
  "thorium-wall": { type: "Wall", size: 1 },
  "thorium-wall-large": { type: "Wall", size: 2 },
  "thruster": { type: "Thruster", size: 4 },
  "tile-logic-display": { type: "TileableLogicDisplay", size: 1 },
  "titan": { type: "ItemTurret", size: 4, range: 390 },
  "titanium-conveyor": { type: "Conveyor", size: 1 },
  "titanium-wall": { type: "Wall", size: 1 },
  "titanium-wall-large": { type: "Wall", size: 2 },
  "tsunami": { type: "LiquidTurret", size: 3, range: 190 },
  "tungsten-wall": { type: "Wall", size: 1 },
  "tungsten-wall-large": { type: "Wall", size: 2 },
  "turbine-condenser": { type: "ThermalGenerator", size: 3 },
  "underflow-duct": { type: "OverflowDuct", size: 1 },
  "underflow-gate": { type: "OverflowGate", size: 1 },
  "unit-cargo-loader": { type: "UnitCargoLoader", size: 3 },
  "unit-cargo-unload-point": { type: "UnitCargoUnloadPoint", size: 2 },
  "unit-repair-tower": { type: "RepairTower", size: 2, range: 100 },
  "unloader": { type: "Unloader", size: 1 },
  "vault": { type: "StorageBlock", size: 3 },
  "vent-condenser": { type: "AttributeCrafter", size: 3 },
  "vibrant-crystal-cluster": { type: "TallBlock", size: 1 },
  "water-extractor": { type: "SolidPump", size: 2 },
  "wave": { type: "LiquidTurret", size: 2, range: 110 },
  "white-tree": { type: "TreeBlock", size: 1 },
  "white-tree-dead": { type: "TreeBlock", size: 1 },
  "world-cell": { type: "MemoryBlock", size: 1 },
  "world-message": { type: "MessageBlock", size: 1 },
  "world-processor": { type: "LogicBlock", size: 1 },
  "world-switch": { type: "SwitchBlock", size: 1 },
  "yellow-stone": { type: "Floor", size: 1 },
  "yellow-stone-boulder": { type: "StaticProp", size: 1 },
  "yellow-stone-plates": { type: "Floor", size: 1 },
  "yellow-stone-vent": { type: "SteamVent", size: 1 },
  "yellow-stone-wall": { type: "StaticWall", size: 1 },
  "yellowcoral": { type: "SeaBush", size: 1 },
};
