// =============================================================================
// vanilla_blocks.js —— 由 tools/gen_vanilla_blocks.py 从 Mindustry v159.7
//   Blocks.java 自动生成，请勿手改；复跑：
//   python3 tools/gen_vanilla_blocks.py <Blocks.java>
//
// 字段：方块内部名 -> { type: 官方 Java 类名, size: 占地, range?: 连接范围,
//   powerProduction?: 每刻发电（PowerGenerator.getDisplayedPowerProduction()，
//     缺省 0；storage 值=原始值，ThermalGenerator 已按 displayEfficiencyScale 折算）,
//   powerUsage?: 每刻耗电（consumePower 的 consPower.usage，缺省 0）,
//   consumeItems?: [[物品, 数量], …]（consumeItem(s)，数量为「每周期」量）,
//   outputItems?: [[物品, 数量], …]（outputItem(s)，每周期量）,
//   ammoItems?: [物品, …]（ItemTurret.ammo(...) 的弹药列表，按出现顺序）,
//   fuelCategories?: ["flammable"|"explosive"|"radioactive", …]（ConsumeItem* 类别）,
//   fuelItems?: {类别: [可烧物品, …]}（按 ConsumeItem* filter 阈值 + Items 属性静态算出）,
//   craftTime?: 制造周期（ticks，缺省该类默认；速率 = 数量*60/craftTime）,
//   itemDuration?: 发电机每烧一个物品的 ticks（速率 = 数量*60/itemDuration）,
//   constructTime?: 单位工厂建造周期（ticks；Reconstructor 的物品输入速率用）,
//   flags?: { hasItems/hasLiquids/outputsLiquid/outputsItems/squareSprite/rotate/
//             rotateDraw/isDuct/armored } }。flags 仅记录与类默认不同的值
//   （squareSprite/rotateDraw 仅记 false，其余仅记 true）。类型是 render_rules.js
//   类型规则表的键；flags 是 js/blending.js 邻居拼接判定的事实来源。
//   rotate / rotateDraw 按类「自身」声明（CLASS_ROTATE/CLASS_ROTATE_DRAW，不解析
//   继承），对应官方 Block.drawDefaultPlanRegion 的旋转条件；通用渲染路径据此
//   决定是否把蓝图 rot 施加到方块贴图上（见 render_rules.isRotatableBlock）。
// =============================================================================
export const VANILLA_BLOCKS = {
  "additive-reconstructor": { type: "Reconstructor", size: 3, powerUsage: 3.0, consumeItems: [["silicon", 40], ["graphite", 40]], constructTime: 600.0 },
  "advanced-launch-pad": { type: "LaunchPad", size: 4, powerUsage: 8.0, flags: { hasItems: true, hasLiquids: true, outputsItems: false } },
  "afflict": { type: "PowerTurret", size: 4, range: 368, powerUsage: 5.0 },
  "air": { type: "AirBlock", size: 1 },
  "air-factory": { type: "UnitFactory", size: 3, powerUsage: 1.2, flags: { hasItems: true, outputsItems: false, rotate: true } },
  "arc": { type: "PowerTurret", size: 1, range: 90, powerUsage: 3.3 },
  "arkycite-floor": { type: "Floor", size: 1 },
  "arkyic-boulder": { type: "Prop", size: 1 },
  "arkyic-stone": { type: "Floor", size: 1 },
  "arkyic-vent": { type: "SteamVent", size: 1 },
  "arkyic-wall": { type: "StaticWall", size: 1 },
  "armored-conveyor": { type: "ArmoredConveyor", size: 1, flags: { hasItems: true } },
  "armored-duct": { type: "Duct", size: 1, flags: { hasItems: true, rotate: true, isDuct: true, armored: true } },
  "atmospheric-concentrator": { type: "HeatCrafter", size: 3, powerUsage: 2.0, flags: { hasItems: true, hasLiquids: true, outputsLiquid: true } },
  "basalt": { type: "Floor", size: 1 },
  "basalt-boulder": { type: "StaticProp", size: 1 },
  "basalt-vent": { type: "SteamVent", size: 1 },
  "basic-assembler-module": { type: "UnitAssemblerModule", size: 5, powerUsage: 3.5, flags: { rotate: true, rotateDraw: false } },
  "battery": { type: "Battery", size: 1 },
  "battery-large": { type: "Battery", size: 3 },
  "beam-link": { type: "LongPowerNode", size: 3 },
  "beam-node": { type: "BeamNode", size: 1, range: 10 },
  "beam-tower": { type: "BeamNode", size: 3, range: 23 },
  "beryllic-boulder": { type: "StaticProp", size: 1 },
  "beryllic-stone": { type: "Floor", size: 1 },
  "beryllic-stone-wall": { type: "StaticWall", size: 1 },
  "beryllium-wall": { type: "Wall", size: 1 },
  "beryllium-wall-large": { type: "Wall", size: 2 },
  "blast-door": { type: "AutoDoor", size: 2 },
  "blast-drill": { type: "Drill", size: 4, powerUsage: 3.0, flags: { hasItems: true, hasLiquids: true } },
  "blast-mixer": { type: "GenericCrafter", size: 2, powerUsage: 0.4, consumeItems: [["pyratite", 1], ["spore-pod", 1]], outputItems: [["blast-compound", 1]], craftTime: 80.0, flags: { hasItems: true, hasLiquids: true } },
  "bluemat": { type: "Floor", size: 1 },
  "boulder": { type: "StaticProp", size: 1 },
  "breach": { type: "ItemTurret", size: 3, range: 190, ammoItems: ["beryllium", "tungsten", "carbide"], flags: { hasItems: true, hasLiquids: true, outputsItems: false } },
  "bridge-conduit": { type: "LiquidBridge", size: 1, range: 4, flags: { hasLiquids: true, outputsLiquid: true } },
  "bridge-conveyor": { type: "BufferedItemBridge", size: 1, range: 4, flags: { hasItems: true } },
  "build-tower": { type: "BuildTurret", size: 3, range: 200, powerUsage: 3.0, flags: { hasLiquids: true } },
  "canvas": { type: "CanvasBlock", size: 2 },
  "carbide-crucible": { type: "HeatCrafter", size: 3, powerUsage: 2.0, consumeItems: [["tungsten", 2], ["graphite", 3]], outputItems: [["carbide", 1]], craftTime: 33.75, flags: { hasItems: true, hasLiquids: true } },
  "carbide-wall": { type: "Wall", size: 1 },
  "carbide-wall-large": { type: "Wall", size: 2 },
  "carbon-boulder": { type: "StaticProp", size: 1 },
  "carbon-stone": { type: "Floor", size: 1 },
  "carbon-vent": { type: "SteamVent", size: 1 },
  "carbon-wall": { type: "StaticWall", size: 1 },
  "char": { type: "Floor", size: 1 },
  "character-overlay": { type: "CharacterOverlay", size: 1, flags: { rotate: true } },
  "character-overlay-white": { type: "CharacterOverlay", size: 1, flags: { rotate: true } },
  "chemical-combustion-chamber": { type: "ConsumeGenerator", size: 3, powerProduction: 9.166666666666666, flags: { hasLiquids: true, outputsLiquid: true } },
  "cliff": { type: "Cliff", size: 1 },
  "cliff-crusher": { type: "WallCrafter", size: 2, powerUsage: 0.18333333333333332, flags: { hasItems: true, rotate: true } },
  "coal-centrifuge": { type: "GenericCrafter", size: 2, powerUsage: 0.7, outputItems: [["coal", 1]], craftTime: 30.0, flags: { hasItems: true, hasLiquids: true, rotateDraw: false } },
  "colored-floor": { type: "ColoredFloor", size: 1 },
  "colored-wall": { type: "ColoredWall", size: 1 },
  "combustion-generator": { type: "ConsumeGenerator", size: 1, powerProduction: 1.0, fuelCategories: ["flammable"], fuelItems: { flammable: ["coal", "spore-pod", "blast-compound", "pyratite"] }, itemDuration: 120.0, flags: { hasLiquids: true, outputsLiquid: true } },
  "command-center": { type: "LegacyCommandCenter", size: 2 },
  "conduit": { type: "Conduit", size: 1, flags: { hasLiquids: true, outputsLiquid: true, rotate: true } },
  "constructor": { type: "Constructor", size: 3, powerUsage: 2.5, flags: { hasItems: true } },
  "container": { type: "StorageBlock", size: 2, flags: { hasItems: true, outputsItems: false } },
  "conveyor": { type: "Conveyor", size: 1, flags: { hasItems: true, rotate: true } },
  "copper-wall": { type: "Wall", size: 1 },
  "copper-wall-large": { type: "Wall", size: 2 },
  "core-acropolis": { type: "CoreBlock", size: 6, flags: { hasItems: true, outputsItems: false } },
  "core-bastion": { type: "CoreBlock", size: 4, flags: { hasItems: true, outputsItems: false } },
  "core-citadel": { type: "CoreBlock", size: 5, flags: { hasItems: true, outputsItems: false } },
  "core-foundation": { type: "CoreBlock", size: 4, flags: { hasItems: true, outputsItems: false } },
  "core-nucleus": { type: "CoreBlock", size: 5, flags: { hasItems: true, outputsItems: false } },
  "core-shard": { type: "CoreBlock", size: 3, flags: { hasItems: true, outputsItems: false } },
  "core-zone": { type: "Floor", size: 1 },
  "crater-stone": { type: "Floor", size: 1 },
  "cryofluid-mixer": { type: "GenericCrafter", size: 2, powerUsage: 1.0, consumeItems: [["titanium", 1]], craftTime: 120.0, flags: { hasItems: true, hasLiquids: true, outputsLiquid: true } },
  "crystal-blocks": { type: "TallBlock", size: 1 },
  "crystal-cluster": { type: "TallBlock", size: 1 },
  "crystal-floor": { type: "Floor", size: 1 },
  "crystal-orbs": { type: "TallBlock", size: 1 },
  "crystalline-boulder": { type: "StaticProp", size: 1 },
  "crystalline-stone": { type: "Floor", size: 1 },
  "crystalline-stone-wall": { type: "StaticWall", size: 1 },
  "crystalline-vent": { type: "SteamVent", size: 1 },
  "cultivator": { type: "AttributeCrafter", size: 2, powerUsage: 1.3333333333333333, outputItems: [["spore-pod", 1]], craftTime: 100.0, flags: { hasItems: true, hasLiquids: true } },
  "cyanogen-synthesizer": { type: "HeatCrafter", size: 3, powerUsage: 2.0, consumeItems: [["graphite", 1]], craftTime: 20.0, flags: { hasItems: true, hasLiquids: true, outputsLiquid: true } },
  "cyclone": { type: "ItemTurret", size: 3, range: 200, ammoItems: ["metaglass", "blast-compound", "plastanium", "surge-alloy"], flags: { hasItems: true, outputsItems: false } },
  "dacite": { type: "Floor", size: 1 },
  "dacite-boulder": { type: "StaticProp", size: 1 },
  "dacite-wall": { type: "StaticWall", size: 1 },
  "dark-metal": { type: "StaticWall", size: 1 },
  "darksand": { type: "Floor", size: 1 },
  "darksand-tainted-water": { type: "ShallowLiquid", size: 1 },
  "darksand-water": { type: "ShallowLiquid", size: 1 },
  "deconstructor": { type: "PayloadDeconstructor", size: 5, powerUsage: 3.0, flags: { hasItems: true } },
  "deep-tainted-water": { type: "Floor", size: 1 },
  "deep-water": { type: "Floor", size: 1 },
  "dense-red-stone": { type: "Floor", size: 1 },
  "differential-generator": { type: "ConsumeGenerator", size: 3, powerProduction: 18.0, consumeItems: [["pyratite", 1]], itemDuration: 220.0, flags: { hasItems: true, hasLiquids: true, outputsLiquid: true, outputsItems: false } },
  "diffuse": { type: "ItemTurret", size: 3, range: 125, ammoItems: ["graphite", "oxide", "silicon"], flags: { hasItems: true, hasLiquids: true, outputsItems: false } },
  "diode": { type: "PowerDiode", size: 1, flags: { rotate: true } },
  "dirt": { type: "Floor", size: 1 },
  "dirt-wall": { type: "StaticWall", size: 1 },
  "disassembler": { type: "Separator", size: 3, powerUsage: 4.0, consumeItems: [["scrap", 1]], craftTime: 15.0, flags: { hasItems: true, hasLiquids: true } },
  "disperse": { type: "ItemTurret", size: 4, range: 310, ammoItems: ["tungsten", "thorium", "silicon", "surge-alloy"], flags: { hasItems: true, hasLiquids: true, outputsItems: false } },
  "distributor": { type: "Router", size: 2, flags: { hasItems: true } },
  "door": { type: "Door", size: 1 },
  "door-large": { type: "Door", size: 2 },
  "duct": { type: "Duct", size: 1, flags: { hasItems: true, rotate: true, isDuct: true } },
  "duct-bridge": { type: "DuctBridge", size: 1, flags: { hasItems: true, isDuct: true } },
  "duct-router": { type: "DuctRouter", size: 1, flags: { hasItems: true, rotate: true } },
  "duct-unloader": { type: "DirectionalUnloader", size: 1, flags: { hasItems: true, rotate: true, isDuct: true } },
  "dune-wall": { type: "StaticWall", size: 1 },
  "duo": { type: "ItemTurret", size: 1, range: 160, ammoItems: ["copper", "graphite", "silicon"], flags: { hasItems: true, outputsItems: false } },
  "electric-heater": { type: "HeatProducer", size: 2, powerUsage: 1.6666666666666667, flags: { hasItems: true, hasLiquids: true, rotate: true, rotateDraw: false } },
  "electrolyzer": { type: "GenericCrafter", size: 3, powerUsage: 1.0, flags: { hasItems: true, hasLiquids: true, outputsLiquid: true, rotate: true } },
  "empty": { type: "EmptyFloor", size: 1 },
  "eruption-drill": { type: "BurstDrill", size: 5, powerUsage: 6.0, flags: { hasItems: true, hasLiquids: true } },
  "exponential-reconstructor": { type: "Reconstructor", size: 7, powerUsage: 13.0, consumeItems: [["silicon", 850], ["titanium", 750], ["plastanium", 650]], constructTime: 5400.0, flags: { hasLiquids: true } },
  "ferric-boulder": { type: "StaticProp", size: 1 },
  "ferric-craters": { type: "Floor", size: 1 },
  "ferric-stone": { type: "Floor", size: 1 },
  "ferric-stone-wall": { type: "StaticWall", size: 1 },
  "flux-reactor": { type: "VariableReactor", size: 5, powerProduction: 300.0, flags: { hasLiquids: true } },
  "force-projector": { type: "ForceProjector", size: 3, powerUsage: 4.0, consumeItems: [["phase-fabric", 1]], flags: { hasItems: true, hasLiquids: true, outputsItems: false } },
  "foreshadow": { type: "ItemTurret", size: 4, range: 500, powerUsage: 10.0, ammoItems: ["surge-alloy"], flags: { hasItems: true, hasLiquids: true, outputsItems: false } },
  "fuse": { type: "ItemTurret", size: 3, range: 90, ammoItems: ["titanium", "thorium"], flags: { hasItems: true, outputsItems: false } },
  "graphite-press": { type: "GenericCrafter", size: 2, consumeItems: [["coal", 2]], outputItems: [["graphite", 1]], craftTime: 90.0, flags: { hasItems: true, hasLiquids: true } },
  "graphitic-wall": { type: "StaticWall", size: 1 },
  "grass": { type: "Floor", size: 1 },
  "ground-factory": { type: "UnitFactory", size: 3, powerUsage: 1.2, flags: { hasItems: true, outputsItems: false, rotate: true } },
  "hail": { type: "ItemTurret", size: 1, range: 235, ammoItems: ["graphite", "silicon", "pyratite"], flags: { hasItems: true, outputsItems: false } },
  "heat-reactor": { type: "HeatProducer", size: 3, consumeItems: [["thorium", 3]], outputItems: [["fissile-matter", 1]], craftTime: 600.0, flags: { hasItems: true, hasLiquids: true, rotate: true, rotateDraw: false } },
  "heat-redirector": { type: "HeatConductor", size: 3, flags: { rotate: true, rotateDraw: false } },
  "heat-router": { type: "HeatConductor", size: 3, flags: { rotate: true, rotateDraw: false } },
  "heat-source": { type: "HeatProducer", size: 1, flags: { hasItems: true, hasLiquids: true, rotate: true, rotateDraw: false } },
  "hotrock": { type: "Floor", size: 1 },
  "hyper-processor": { type: "LogicBlock", size: 3, range: 8, flags: { hasLiquids: true } },
  "ice": { type: "Floor", size: 1 },
  "ice-snow": { type: "Floor", size: 1 },
  "ice-wall": { type: "StaticWall", size: 1 },
  "illuminator": { type: "LightBlock", size: 1, powerUsage: 0.05 },
  "impact-drill": { type: "BurstDrill", size: 4, powerUsage: 2.6666666666666665, flags: { hasItems: true, hasLiquids: true } },
  "impact-reactor": { type: "ImpactReactor", size: 4, powerProduction: 130.0, powerUsage: 25.0, consumeItems: [["blast-compound", 1]], itemDuration: 140.0, flags: { hasItems: true, hasLiquids: true, outputsItems: false } },
  "impulse-pump": { type: "Pump", size: 3, powerUsage: 1.3, flags: { hasLiquids: true, outputsLiquid: true } },
  "incinerator": { type: "Incinerator", size: 1, powerUsage: 0.5, flags: { hasLiquids: true } },
  "interplanetary-accelerator": { type: "Accelerator", size: 7, powerUsage: 10.0, flags: { hasItems: true, outputsItems: false } },
  "inverted-sorter": { type: "Sorter", size: 1, flags: { outputsItems: true } },
  "item-source": { type: "ItemSource", size: 1, flags: { hasItems: true } },
  "item-void": { type: "ItemVoid", size: 1 },
  "junction": { type: "Junction", size: 1, flags: { outputsItems: true } },
  "kiln": { type: "GenericCrafter", size: 2, powerUsage: 0.6, consumeItems: [["lead", 1], ["sand", 1]], outputItems: [["metaglass", 1]], craftTime: 30.0, flags: { hasItems: true, hasLiquids: true } },
  "lancer": { type: "PowerTurret", size: 2, range: 165, powerUsage: 6.0 },
  "landing-pad": { type: "LandingPad", size: 4, flags: { hasItems: true, hasLiquids: true } },
  "large-canvas": { type: "CanvasBlock", size: 3 },
  "large-cliff-crusher": { type: "WallCrafter", size: 3, powerUsage: 1.0, consumeItems: [["graphite", 1]], flags: { hasItems: true, hasLiquids: true, rotate: true } },
  "large-constructor": { type: "Constructor", size: 5, powerUsage: 3.0, flags: { hasItems: true } },
  "large-logic-display": { type: "LogicDisplay", size: 6 },
  "large-payload-mass-driver": { type: "PayloadMassDriver", size: 5, range: 2100, powerUsage: 3.0, flags: { rotate: true } },
  "large-plasma-bore": { type: "BeamDrill", size: 3, range: 6, powerUsage: 0.8, flags: { hasItems: true, hasLiquids: true, rotate: true } },
  "large-shield-projector": { type: "BaseShield", size: 4, powerUsage: 5.0 },
  "laser-drill": { type: "Drill", size: 3, powerUsage: 1.1, flags: { hasItems: true, hasLiquids: true } },
  "launch-pad": { type: "LaunchPad", size: 3, powerUsage: 4.0, flags: { hasItems: true, outputsItems: false } },
  "legacy-mech-pad": { type: "LegacyMechPad", size: 1 },
  "legacy-unit-factory": { type: "LegacyUnitFactory", size: 1, flags: { hasItems: true } },
  "legacy-unit-factory-air": { type: "LegacyUnitFactory", size: 1, flags: { hasItems: true } },
  "legacy-unit-factory-ground": { type: "LegacyUnitFactory", size: 1, flags: { hasItems: true } },
  "liquid-container": { type: "LiquidRouter", size: 2, flags: { hasLiquids: true, outputsLiquid: true } },
  "liquid-junction": { type: "LiquidJunction", size: 1, flags: { hasLiquids: true, outputsLiquid: true } },
  "liquid-router": { type: "LiquidRouter", size: 1, flags: { hasLiquids: true, outputsLiquid: true } },
  "liquid-source": { type: "LiquidSource", size: 1, flags: { hasLiquids: true, outputsLiquid: true } },
  "liquid-tank": { type: "LiquidRouter", size: 3, flags: { hasLiquids: true, outputsLiquid: true } },
  "liquid-void": { type: "LiquidVoid", size: 1, flags: { hasLiquids: true } },
  "logic-display": { type: "LogicDisplay", size: 3 },
  "logic-processor": { type: "LogicBlock", size: 2, range: 8 },
  "lustre": { type: "ContinuousTurret", size: 4, range: 250, powerUsage: 3.3333333333333335, flags: { hasLiquids: true } },
  "magmarock": { type: "Floor", size: 1 },
  "malign": { type: "PowerTurret", size: 5, range: 410, powerUsage: 40.0 },
  "mass-driver": { type: "MassDriver", size: 3, range: 440, powerUsage: 1.75, flags: { hasItems: true } },
  "mech-assembler": { type: "UnitAssembler", size: 5, powerUsage: 3.0, flags: { hasItems: true, hasLiquids: true, rotate: true, rotateDraw: false } },
  "mech-fabricator": { type: "UnitFactory", size: 3, powerUsage: 1.5, flags: { hasItems: true, outputsItems: false, rotate: true } },
  "mech-refabricator": { type: "Reconstructor", size: 3, powerUsage: 2.5, consumeItems: [["silicon", 50], ["tungsten", 40]], constructTime: 2700.0, flags: { hasLiquids: true } },
  "mechanical-drill": { type: "Drill", size: 2, flags: { hasItems: true, hasLiquids: true } },
  "mechanical-pump": { type: "Pump", size: 1, flags: { hasLiquids: true, outputsLiquid: true } },
  "meltdown": { type: "LaserTurret", size: 4, range: 195, powerUsage: 17.0, flags: { hasLiquids: true } },
  "melter": { type: "GenericCrafter", size: 1, powerUsage: 1.0, consumeItems: [["scrap", 1]], craftTime: 10.0, flags: { hasItems: true, hasLiquids: true, outputsLiquid: true } },
  "memory-bank": { type: "MemoryBlock", size: 2 },
  "memory-cell": { type: "MemoryBlock", size: 1 },
  "mend-projector": { type: "MendProjector", size: 2, range: 85, powerUsage: 1.5, consumeItems: [["phase-fabric", 1]], flags: { hasItems: true, outputsItems: false } },
  "mender": { type: "MendProjector", size: 1, range: 40, powerUsage: 0.3, consumeItems: [["silicon", 1]], flags: { hasItems: true, outputsItems: false } },
  "message": { type: "MessageBlock", size: 1 },
  "metal-tiles-1": { type: "Floor", size: 1 },
  "metal-tiles-10": { type: "Floor", size: 1 },
  "metal-tiles-11": { type: "Floor", size: 1 },
  "metal-tiles-12": { type: "Floor", size: 1 },
  "metal-tiles-13": { type: "Floor", size: 1 },
  "metal-tiles-2": { type: "Floor", size: 1 },
  "metal-tiles-3": { type: "Floor", size: 1 },
  "metal-tiles-4": { type: "Floor", size: 1 },
  "metal-tiles-5": { type: "Floor", size: 1 },
  "metal-tiles-6": { type: "Floor", size: 1 },
  "metal-tiles-7": { type: "Floor", size: 1 },
  "metal-tiles-8": { type: "Floor", size: 1 },
  "metal-tiles-9": { type: "Floor", size: 1 },
  "metal-wall-1": { type: "StaticWall", size: 1 },
  "metal-wall-2": { type: "StaticWall", size: 1 },
  "metal-wall-3": { type: "StaticWall", size: 1 },
  "micro-processor": { type: "LogicBlock", size: 1 },
  "molten-slag": { type: "Floor", size: 1 },
  "moss": { type: "Floor", size: 1 },
  "mud": { type: "Floor", size: 1 },
  "multi-press": { type: "GenericCrafter", size: 3, powerUsage: 1.8, consumeItems: [["coal", 3]], outputItems: [["graphite", 2]], craftTime: 30.0, flags: { hasItems: true, hasLiquids: true } },
  "multiplicative-reconstructor": { type: "Reconstructor", size: 5, powerUsage: 6.0, consumeItems: [["silicon", 130], ["titanium", 80], ["metaglass", 40]], constructTime: 1800.0 },
  "naval-factory": { type: "UnitFactory", size: 3, powerUsage: 1.2, flags: { hasItems: true, outputsItems: false, rotate: true } },
  "neoplasia-reactor": { type: "HeaterGenerator", size: 5, range: 4, powerProduction: 140.0, consumeItems: [["phase-fabric", 1]], itemDuration: 180.0, flags: { hasLiquids: true, outputsLiquid: true, rotate: true, rotateDraw: false } },
  "oil-extractor": { type: "Fracker", size: 3, powerUsage: 3.0, consumeItems: [["sand", 1]], flags: { hasItems: true, hasLiquids: true, outputsLiquid: true, outputsItems: false } },
  "overdrive-dome": { type: "OverdriveProjector", size: 3, range: 200, powerUsage: 10.0, consumeItems: [["phase-fabric", 1], ["silicon", 1]], flags: { hasItems: true, outputsItems: false } },
  "overdrive-projector": { type: "OverdriveProjector", size: 2, powerUsage: 3.5, consumeItems: [["phase-fabric", 1]], flags: { hasItems: true, outputsItems: false } },
  "overflow-duct": { type: "OverflowDuct", size: 1, flags: { hasItems: true, rotate: true } },
  "overflow-gate": { type: "OverflowGate", size: 1, flags: { hasItems: true } },
  "oxidation-chamber": { type: "HeatProducer", size: 3, powerUsage: 0.5, consumeItems: [["beryllium", 1]], outputItems: [["oxide", 1]], craftTime: 120.0, flags: { hasItems: true, hasLiquids: true, rotate: true, rotateDraw: false } },
  "parallax": { type: "TractorBeamTurret", size: 2, range: 300, powerUsage: 3.3 },
  "payload-conveyor": { type: "PayloadConveyor", size: 1, flags: { rotate: true } },
  "payload-loader": { type: "PayloadLoader", size: 3, powerUsage: 2.0, flags: { hasItems: true, hasLiquids: true, outputsItems: false, rotate: true } },
  "payload-mass-driver": { type: "PayloadMassDriver", size: 3, range: 700, powerUsage: 0.5, flags: { rotate: true } },
  "payload-router": { type: "PayloadRouter", size: 1 },
  "payload-source": { type: "PayloadSource", size: 5, flags: { rotate: true } },
  "payload-unloader": { type: "PayloadUnloader", size: 3, powerUsage: 2.0, flags: { hasItems: true, hasLiquids: true, outputsLiquid: true } },
  "payload-void": { type: "PayloadVoid", size: 5 },
  "pebbles": { type: "OverlayFloor", size: 1 },
  "phase-conduit": { type: "LiquidBridge", size: 1, range: 12, powerUsage: 0.3, flags: { hasLiquids: true, outputsLiquid: true } },
  "phase-conveyor": { type: "ItemBridge", size: 1, range: 12, powerUsage: 0.3, flags: { hasItems: true } },
  "phase-heater": { type: "HeatProducer", size: 2, consumeItems: [["phase-fabric", 1]], craftTime: 480.0, flags: { hasItems: true, hasLiquids: true, rotate: true, rotateDraw: false } },
  "phase-synthesizer": { type: "HeatCrafter", size: 3, powerUsage: 8.0, consumeItems: [["thorium", 2], ["sand", 6]], outputItems: [["phase-fabric", 1]], craftTime: 30.0, flags: { hasItems: true, hasLiquids: true } },
  "phase-wall": { type: "Wall", size: 1 },
  "phase-wall-large": { type: "Wall", size: 2 },
  "phase-weaver": { type: "GenericCrafter", size: 2, powerUsage: 5.0, consumeItems: [["thorium", 4], ["sand", 10]], outputItems: [["phase-fabric", 1]], craftTime: 120.0, flags: { hasItems: true, hasLiquids: true } },
  "pine": { type: "StaticTree", size: 1 },
  "plasma-bore": { type: "BeamDrill", size: 2, range: 5, powerUsage: 0.15, flags: { hasItems: true, hasLiquids: true, rotate: true } },
  "plastanium-compressor": { type: "GenericCrafter", size: 2, powerUsage: 3.0, consumeItems: [["titanium", 2]], outputItems: [["plastanium", 1]], craftTime: 60.0, flags: { hasItems: true, hasLiquids: true } },
  "plastanium-conveyor": { type: "StackConveyor", size: 1, flags: { hasItems: true, rotate: true } },
  "plastanium-wall": { type: "Wall", size: 1 },
  "plastanium-wall-large": { type: "Wall", size: 2 },
  "plated-conduit": { type: "ArmoredConduit", size: 1, flags: { hasLiquids: true, outputsLiquid: true } },
  "pneumatic-drill": { type: "Drill", size: 2, flags: { hasItems: true, hasLiquids: true } },
  "pooled-cryofluid": { type: "Floor", size: 1 },
  "power-node": { type: "PowerNode", size: 1 },
  "power-node-large": { type: "PowerNode", size: 2 },
  "power-source": { type: "PowerSource", size: 1, powerProduction: 16666.666666666668 },
  "power-void": { type: "PowerVoid", size: 1 },
  "prime-refabricator": { type: "Reconstructor", size: 5, powerUsage: 4.5, consumeItems: [["thorium", 80], ["silicon", 100]], constructTime: 3600.0, flags: { hasLiquids: true } },
  "pulse-conduit": { type: "Conduit", size: 1, flags: { hasLiquids: true, outputsLiquid: true, rotate: true } },
  "pulverizer": { type: "GenericCrafter", size: 1, powerUsage: 0.5, consumeItems: [["scrap", 1]], outputItems: [["sand", 1]], craftTime: 40.0, flags: { hasItems: true, hasLiquids: true } },
  "pur-bush": { type: "SeaBush", size: 1 },
  "pyratite-mixer": { type: "GenericCrafter", size: 2, powerUsage: 0.2, consumeItems: [["coal", 1], ["lead", 2], ["sand", 2]], outputItems: [["pyratite", 1]], craftTime: 80.0, flags: { hasItems: true, hasLiquids: true } },
  "pyrolysis-generator": { type: "ConsumeGenerator", size: 3, powerProduction: 23.333333333333332, flags: { hasLiquids: true, outputsLiquid: true } },
  "radar": { type: "Radar", size: 1, powerUsage: 0.6 },
  "red-diamond-wall": { type: "StaticTree", size: 1 },
  "red-ice": { type: "Floor", size: 1 },
  "red-ice-boulder": { type: "StaticProp", size: 1 },
  "red-ice-wall": { type: "StaticWall", size: 1 },
  "red-stone": { type: "Floor", size: 1 },
  "red-stone-boulder": { type: "StaticProp", size: 1 },
  "red-stone-vent": { type: "SteamVent", size: 1 },
  "red-stone-wall": { type: "StaticWall", size: 1 },
  "redmat": { type: "Floor", size: 1 },
  "redweed": { type: "Seaweed", size: 1 },
  "regen-projector": { type: "RegenProjector", size: 3, range: 28, powerUsage: 1.0, consumeItems: [["phase-fabric", 1]], flags: { hasItems: true, hasLiquids: true, outputsItems: false, rotateDraw: false } },
  "regolith": { type: "Floor", size: 1 },
  "regolith-wall": { type: "StaticWall", size: 1 },
  "reinforced-bridge-conduit": { type: "DirectionLiquidBridge", size: 1, range: 4, flags: { hasLiquids: true, outputsLiquid: true } },
  "reinforced-conduit": { type: "ArmoredConduit", size: 1, flags: { hasLiquids: true, outputsLiquid: true } },
  "reinforced-container": { type: "StorageBlock", size: 2, flags: { hasItems: true, outputsItems: false } },
  "reinforced-liquid-container": { type: "LiquidRouter", size: 2, flags: { hasLiquids: true, outputsLiquid: true } },
  "reinforced-liquid-junction": { type: "LiquidJunction", size: 1, flags: { hasLiquids: true, outputsLiquid: true } },
  "reinforced-liquid-router": { type: "LiquidRouter", size: 1, flags: { hasLiquids: true, outputsLiquid: true } },
  "reinforced-liquid-tank": { type: "LiquidRouter", size: 3, flags: { hasLiquids: true, outputsLiquid: true } },
  "reinforced-message": { type: "MessageBlock", size: 1 },
  "reinforced-payload-conveyor": { type: "PayloadConveyor", size: 1, flags: { rotate: true } },
  "reinforced-payload-router": { type: "PayloadRouter", size: 1 },
  "reinforced-pump": { type: "Pump", size: 2, flags: { hasLiquids: true, outputsLiquid: true } },
  "reinforced-surge-wall": { type: "Wall", size: 1 },
  "reinforced-surge-wall-large": { type: "Wall", size: 2 },
  "reinforced-vault": { type: "StorageBlock", size: 3, flags: { hasItems: true, outputsItems: false } },
  "remove-ore": { type: "RemoveOre", size: 1 },
  "remove-wall": { type: "RemoveWall", size: 1 },
  "repair-point": { type: "RepairTurret", size: 1, flags: { hasLiquids: true } },
  "repair-turret": { type: "RepairTurret", size: 2, flags: { hasLiquids: true } },
  "rhyolite": { type: "Floor", size: 1 },
  "rhyolite-boulder": { type: "StaticProp", size: 1 },
  "rhyolite-crater": { type: "Floor", size: 1 },
  "rhyolite-vent": { type: "SteamVent", size: 1 },
  "rhyolite-wall": { type: "StaticWall", size: 1 },
  "ripple": { type: "ItemTurret", size: 3, range: 290, ammoItems: ["graphite", "silicon", "pyratite", "blast-compound", "plastanium"], flags: { hasItems: true, outputsItems: false } },
  "rotary-pump": { type: "Pump", size: 2, powerUsage: 0.3, flags: { hasLiquids: true, outputsLiquid: true } },
  "rough-rhyolite": { type: "Floor", size: 1 },
  "router": { type: "Router", size: 1, flags: { hasItems: true } },
  "rtg-generator": { type: "ConsumeGenerator", size: 2, powerProduction: 4.5, fuelCategories: ["radioactive"], fuelItems: { radioactive: ["thorium", "phase-fabric", "fissile-matter"] }, itemDuration: 840.0, flags: { hasLiquids: true, outputsLiquid: true } },
  "rune-overlay": { type: "RuneOverlay", size: 1 },
  "rune-overlay-crux": { type: "RuneOverlay", size: 1 },
  "salt": { type: "Floor", size: 1 },
  "salt-wall": { type: "StaticWall", size: 1 },
  "salvo": { type: "ItemTurret", size: 2, range: 190, ammoItems: ["copper", "graphite", "pyratite", "silicon", "thorium"], flags: { hasItems: true, outputsItems: false } },
  "sand-boulder": { type: "StaticProp", size: 1 },
  "sand-floor": { type: "Floor", size: 1 },
  "sand-wall": { type: "StaticWall", size: 1 },
  "sand-water": { type: "ShallowLiquid", size: 1 },
  "scathe": { type: "ItemTurret", size: 4, range: 1350, ammoItems: ["carbide", "phase-fabric", "surge-alloy"], flags: { hasItems: true, hasLiquids: true, outputsItems: false, rotate: true } },
  "scatter": { type: "ItemTurret", size: 2, range: 220, ammoItems: ["scrap", "lead", "metaglass"], flags: { hasItems: true, outputsItems: false } },
  "scorch": { type: "ItemTurret", size: 1, range: 60, ammoItems: ["coal", "pyratite"], flags: { hasItems: true, outputsItems: false } },
  "scrap-wall": { type: "Wall", size: 1 },
  "scrap-wall-gigantic": { type: "Wall", size: 4 },
  "scrap-wall-huge": { type: "Wall", size: 3 },
  "scrap-wall-large": { type: "Wall", size: 2 },
  "segment": { type: "PointDefenseTurret", size: 2, range: 180, powerUsage: 8.0 },
  "separator": { type: "Separator", size: 2, powerUsage: 1.1, flags: { hasItems: true, hasLiquids: true } },
  "shale": { type: "Floor", size: 1 },
  "shale-boulder": { type: "StaticProp", size: 1 },
  "shale-wall": { type: "StaticWall", size: 1 },
  "shallow-water": { type: "Floor", size: 1 },
  "shield-projector": { type: "BaseShield", size: 3, powerUsage: 5.0 },
  "shielded-wall": { type: "ShieldWall", size: 2, powerUsage: 0.05 },
  "ship-assembler": { type: "UnitAssembler", size: 5, powerUsage: 2.5, flags: { hasItems: true, hasLiquids: true, rotate: true, rotateDraw: false } },
  "ship-fabricator": { type: "UnitFactory", size: 3, powerUsage: 1.5, flags: { hasItems: true, outputsItems: false, rotate: true } },
  "ship-refabricator": { type: "Reconstructor", size: 3, powerUsage: 2.5, consumeItems: [["silicon", 60], ["tungsten", 40]], constructTime: 3000.0, flags: { hasLiquids: true } },
  "shock-mine": { type: "ShockMine", size: 1 },
  "shockwave-tower": { type: "ShockwaveTower", size: 3, range: 170, powerUsage: 1.6666666666666667, flags: { hasLiquids: true } },
  "shrubs": { type: "StaticWall", size: 1 },
  "silicon-arc-furnace": { type: "GenericCrafter", size: 3, powerUsage: 5.0, consumeItems: [["graphite", 1], ["sand", 4]], outputItems: [["silicon", 4]], craftTime: 50.0, flags: { hasItems: true } },
  "silicon-crucible": { type: "AttributeCrafter", size: 3, powerUsage: 4.0, consumeItems: [["coal", 4], ["sand", 6], ["pyratite", 1]], outputItems: [["silicon", 8]], craftTime: 90.0, flags: { hasItems: true } },
  "silicon-smelter": { type: "GenericCrafter", size: 2, powerUsage: 0.5, consumeItems: [["coal", 1], ["sand", 2]], outputItems: [["silicon", 1]], craftTime: 40.0, flags: { hasItems: true } },
  "slag-centrifuge": { type: "GenericCrafter", size: 3, powerUsage: 0.03333333333333333, consumeItems: [["sand", 1]], craftTime: 120.0, flags: { hasItems: true, hasLiquids: true, outputsLiquid: true } },
  "slag-heater": { type: "HeatProducer", size: 3, flags: { hasItems: true, hasLiquids: true, rotate: true, rotateDraw: false } },
  "slag-incinerator": { type: "ItemIncinerator", size: 1, flags: { hasLiquids: true } },
  "small-deconstructor": { type: "PayloadDeconstructor", size: 3, powerUsage: 1.0, flags: { hasItems: true } },
  "small-heat-redirector": { type: "HeatConductor", size: 2, flags: { rotate: true, rotateDraw: false } },
  "smite": { type: "ItemTurret", size: 5, range: 300, ammoItems: ["surge-alloy"], flags: { hasItems: true, hasLiquids: true, outputsItems: false } },
  "snow": { type: "Floor", size: 1 },
  "snow-boulder": { type: "StaticProp", size: 1 },
  "snow-pine": { type: "StaticTree", size: 1 },
  "snow-wall": { type: "StaticWall", size: 1 },
  "solar-panel": { type: "SolarGenerator", size: 1, powerProduction: 0.12 },
  "solar-panel-large": { type: "SolarGenerator", size: 3, powerProduction: 1.6 },
  "sorter": { type: "Sorter", size: 1, flags: { outputsItems: true } },
  "space": { type: "Floor", size: 1 },
  "spawn": { type: "SpawnBlock", size: 1 },
  "spectre": { type: "ItemTurret", size: 4, range: 260, ammoItems: ["graphite", "thorium", "pyratite"], flags: { hasItems: true, hasLiquids: true, outputsItems: false } },
  "spore-cluster": { type: "Prop", size: 1 },
  "spore-moss": { type: "Floor", size: 1 },
  "spore-pine": { type: "StaticTree", size: 1 },
  "spore-press": { type: "GenericCrafter", size: 2, powerUsage: 0.7, consumeItems: [["spore-pod", 1]], craftTime: 20.0, flags: { hasItems: true, hasLiquids: true, outputsLiquid: true } },
  "spore-wall": { type: "StaticWall", size: 1 },
  "steam-generator": { type: "ConsumeGenerator", size: 2, powerProduction: 5.5, fuelCategories: ["flammable"], fuelItems: { flammable: ["coal", "spore-pod", "blast-compound", "pyratite"] }, itemDuration: 90.0, flags: { hasLiquids: true, outputsLiquid: true } },
  "stone": { type: "Floor", size: 1 },
  "stone-vent": { type: "SteamVent", size: 1 },
  "stone-wall": { type: "StaticWall", size: 1 },
  "sublimate": { type: "ContinuousLiquidTurret", size: 3, range: 130, flags: { hasLiquids: true } },
  "surge-conveyor": { type: "StackConveyor", size: 1, powerUsage: 0.016666666666666666, flags: { hasItems: true, rotate: true } },
  "surge-crucible": { type: "HeatCrafter", size: 3, powerUsage: 1.5, consumeItems: [["silicon", 3]], outputItems: [["surge-alloy", 1]], craftTime: 45.0, flags: { hasItems: true, hasLiquids: true } },
  "surge-router": { type: "StackRouter", size: 1, powerUsage: 0.05, flags: { hasItems: true } },
  "surge-smelter": { type: "GenericCrafter", size: 3, powerUsage: 4.0, consumeItems: [["copper", 3], ["lead", 4], ["titanium", 2], ["silicon", 3]], outputItems: [["surge-alloy", 1]], craftTime: 75.0, flags: { hasItems: true, hasLiquids: true } },
  "surge-tower": { type: "PowerNode", size: 2 },
  "surge-wall": { type: "Wall", size: 1 },
  "surge-wall-large": { type: "Wall", size: 2 },
  "swarmer": { type: "ItemTurret", size: 2, range: 240, ammoItems: ["blast-compound", "pyratite", "surge-alloy"], flags: { hasItems: true, outputsItems: false } },
  "switch": { type: "SwitchBlock", size: 1 },
  "tainted-water": { type: "Floor", size: 1 },
  "tank-assembler": { type: "UnitAssembler", size: 5, powerUsage: 2.5, flags: { hasItems: true, hasLiquids: true, rotate: true, rotateDraw: false } },
  "tank-fabricator": { type: "UnitFactory", size: 3, powerUsage: 1.5, flags: { hasItems: true, outputsItems: false, rotate: true } },
  "tank-refabricator": { type: "Reconstructor", size: 3, powerUsage: 3.0, consumeItems: [["silicon", 40], ["tungsten", 30]], constructTime: 1800.0, flags: { hasLiquids: true } },
  "tar": { type: "Floor", size: 1 },
  "tendrils": { type: "OverlayFloor", size: 1 },
  "tetrative-reconstructor": { type: "Reconstructor", size: 9, powerUsage: 25.0, consumeItems: [["silicon", 1000], ["plastanium", 600], ["surge-alloy", 500], ["phase-fabric", 350]], constructTime: 14400.0, flags: { hasLiquids: true } },
  "thermal-generator": { type: "ThermalGenerator", size: 2, powerProduction: 1.8, flags: { hasLiquids: true, outputsLiquid: true } },
  "thorium-reactor": { type: "NuclearReactor", size: 3, powerProduction: 15.0, consumeItems: [["thorium", 1]], itemDuration: 360.0, flags: { hasItems: true, hasLiquids: true, outputsItems: false } },
  "thorium-wall": { type: "Wall", size: 1 },
  "thorium-wall-large": { type: "Wall", size: 2 },
  "thruster": { type: "Thruster", size: 4, flags: { rotate: true } },
  "tile-logic-display": { type: "TileableLogicDisplay", size: 1 },
  "titan": { type: "ItemTurret", size: 4, range: 390, ammoItems: ["thorium", "carbide", "oxide"], flags: { hasItems: true, hasLiquids: true, outputsItems: false } },
  "titanium-conveyor": { type: "Conveyor", size: 1, flags: { hasItems: true, rotate: true } },
  "titanium-wall": { type: "Wall", size: 1 },
  "titanium-wall-large": { type: "Wall", size: 2 },
  "tsunami": { type: "LiquidTurret", size: 3, range: 190, flags: { hasLiquids: true } },
  "tungsten-wall": { type: "Wall", size: 1 },
  "tungsten-wall-large": { type: "Wall", size: 2 },
  "turbine-condenser": { type: "ThermalGenerator", size: 3, powerProduction: 3.0, flags: { hasLiquids: true, outputsLiquid: true } },
  "underflow-duct": { type: "OverflowDuct", size: 1, flags: { hasItems: true, rotate: true } },
  "underflow-gate": { type: "OverflowGate", size: 1, flags: { hasItems: true } },
  "unit-cargo-loader": { type: "UnitCargoLoader", size: 3, powerUsage: 0.13333333333333333, flags: { hasItems: true, hasLiquids: true, outputsItems: false } },
  "unit-cargo-unload-point": { type: "UnitCargoUnloadPoint", size: 2, flags: { hasItems: true } },
  "unit-repair-tower": { type: "RepairTower", size: 2, range: 100, powerUsage: 1.0, flags: { hasLiquids: true } },
  "unloader": { type: "Unloader", size: 1, flags: { hasItems: true } },
  "vault": { type: "StorageBlock", size: 3, flags: { hasItems: true, outputsItems: false } },
  "vent-condenser": { type: "AttributeCrafter", size: 3, powerUsage: 0.5, flags: { hasItems: true, hasLiquids: true, outputsLiquid: true } },
  "vibrant-crystal-cluster": { type: "TallBlock", size: 1 },
  "water-extractor": { type: "SolidPump", size: 2, powerUsage: 1.5, flags: { hasLiquids: true, outputsLiquid: true } },
  "wave": { type: "LiquidTurret", size: 2, range: 110, flags: { hasLiquids: true } },
  "white-tree": { type: "TreeBlock", size: 1 },
  "white-tree-dead": { type: "TreeBlock", size: 1 },
  "world-cell": { type: "MemoryBlock", size: 1 },
  "world-message": { type: "MessageBlock", size: 1 },
  "world-processor": { type: "LogicBlock", size: 1 },
  "world-switch": { type: "SwitchBlock", size: 1 },
  "yellow-stone": { type: "Floor", size: 1 },
  "yellow-stone-boulder": { type: "StaticProp", size: 1 },
  "yellow-stone-plates": { type: "Floor", size: 1 },
  "yellow-stone-vent": { type: "SteamVent", size: 1 },
  "yellow-stone-wall": { type: "StaticWall", size: 1 },
  "yellowcoral": { type: "SeaBush", size: 1 },
};
