#!/usr/bin/env python3
# 自动生成：Mindustry v159.7 方块类型的类级默认属性（继承解析后）。请勿手改。
# 由 tools/gen_vanilla_blocks.py --src-root <core/src/mindustry> 生成。
TYPE_FLAGS = {
    'AIController': {'rot': True},
    'Accelerator': {'hi': True, 'oi': False},
    'AcceleratorBuild': {'hi': True, 'oi': False},
    'AmmoEntry': {'oi': False, 'rot': True},
    'ArmoredConduit': {'hl': True, 'ol': True, 'rot': True},
    'ArmoredConduitBuild': {'hl': True, 'ol': True, 'rot': True},
    'ArmoredConveyor': {'hi': True, 'nsb': True, 'rot': True},
    'ArmoredConveyorBuild': {'hi': True, 'nsb': True, 'rot': True},
    'AssemblerAI': {'rot': True},
    'AssemblerUnitPlan': {'hi': True, 'rot': True},
    'AttributeCrafter': {'hi': True, 'hl': True, 'oi': 'dep'},
    'AttributeCrafterBuild': {'hi': True, 'hl': True, 'oi': 'dep'},
    'BeamDrill': {'hi': True, 'oi': True, 'rot': True},
    'BeamDrillBuild': {'hi': True, 'oi': True, 'rot': True},
    'BlockProducer': {'hi': True, 'rot': True},
    'BlockProducerBuild': {'hi': True, 'rot': True},
    'Blocks': {'hi': True, 'hl': True, 'ol': True, 'rot': True},
    'BoostAI': {'rot': True},
    'BufferedItemBridge': {'hi': True},
    'BufferedItemBridgeBuild': {'hi': True},
    'BuildWeapon': {'rot': True},
    'BuilderAI': {'rot': True},
    'BulletEntry': {'oi': False, 'rot': True},
    'BurstDrill': {'hi': True, 'hl': True},
    'BurstDrillBuild': {'hi': True, 'hl': True},
    'CargoAI': {'rot': True},
    'CharOverlayDataStruct': {'rot': True},
    'CharacterOverlay': {'rot': True},
    'CommandAI': {'rot': True},
    'Conduit': {'hl': True, 'ol': True, 'rot': True},
    'ConduitBuild': {'hl': True, 'ol': True, 'rot': True},
    'Constructor': {'hi': True, 'rot': True},
    'ConstructorBuild': {'hi': True, 'rot': True},
    'ConsumeCoolant': {'hl': True},
    'ConsumeGenerator': {'hl': True, 'oi': False, 'ol': True},
    'ConsumeGeneratorBuild': {'hl': True, 'oi': False, 'ol': True},
    'ConsumeItemCharged': {'hi': True},
    'ConsumeItemDynamic': {'hi': True},
    'ConsumeItemEfficiency': {'hi': True},
    'ConsumeItemExplode': {'hi': True},
    'ConsumeItemExplosive': {'hi': True},
    'ConsumeItemFilter': {'hi': True},
    'ConsumeItemFlammable': {'hi': True},
    'ConsumeItemList': {'hi': True},
    'ConsumeItemRadioactive': {'hi': True},
    'ConsumeItems': {'hi': True},
    'ConsumeLiquid': {'hl': True},
    'ConsumeLiquidBase': {'hl': True},
    'ConsumeLiquidFilter': {'hl': True},
    'ConsumeLiquidFlammable': {'hl': True},
    'ConsumeLiquids': {'hl': True},
    'ConsumeLiquidsDynamic': {'hl': True},
    'ContainerStat': {'hi': True},
    'ContinuousLiquidTurret': {'hl': True, 'oi': False, 'rot': True},
    'ContinuousLiquidTurretBuild': {'hl': True, 'oi': False, 'rot': True},
    'ContinuousTurret': {'oi': False, 'rot': True},
    'ContinuousTurretBuild': {'oi': False, 'rot': True},
    'Conveyor': {'hi': True, 'rot': True},
    'ConveyorBuild': {'hi': True, 'rot': True},
    'CoreBlock': {'hi': True, 'oi': False},
    'CoreBuild': {'hi': True},
    'DefenderAI': {'rot': True},
    'DirectionBridge': {'rot': True},
    'DirectionBridgeBuild': {'rot': True},
    'DirectionLiquidBridge': {'hl': True, 'ol': True, 'rot': True},
    'DirectionalUnloader': {'duct': True, 'hi': True, 'rot': True},
    'DirectionalUnloaderBuild': {'duct': True, 'hi': True, 'rot': True},
    'Drill': {'hi': True, 'hl': True},
    'DrillBuild': {'hi': True, 'hl': True},
    'DriverBulletData': {'hi': True},
    'Duct': {'duct': True, 'hi': True, 'nsb': True, 'rot': True},
    'DuctBridge': {'duct': True, 'hi': True, 'rot': True},
    'DuctBridgeBuild': {'hl': True, 'ol': True, 'rot': True},
    'DuctBuild': {'duct': True, 'hi': True, 'nsb': True, 'rot': True},
    'DuctJunction': {'hi': True, 'oi': True},
    'DuctJunctionBuild': {'hi': True, 'oi': True},
    'DuctRouter': {'hi': True, 'rot': True},
    'DuctRouterBuild': {'hi': True, 'rot': True},
    'EffectEntry': {'rot': True},
    'FlyingAI': {'rot': True},
    'FlyingFollowAI': {'rot': True},
    'ForceBuild': {'hi': True, 'hl': True, 'oi': False},
    'ForceProjector': {'hi': True, 'hl': True, 'oi': False},
    'Fracker': {'hi': True, 'hl': True, 'oi': False, 'ol': True},
    'FrackerBuild': {'hi': True, 'hl': True, 'oi': False, 'ol': True},
    'GeneratorBuild': {'oi': False},
    'GenericCrafter': {'hi': True, 'hl': True, 'oi': 'dep'},
    'GenericCrafterBuild': {'hi': True, 'hl': True, 'oi': 'dep'},
    'GroundAI': {'rot': True},
    'HealBeamMount': {'rot': True},
    'HeatConductor': {'rot': True},
    'HeatConductorBuild': {'rot': True},
    'HeatCrafter': {'hi': True, 'hl': True, 'oi': 'dep'},
    'HeatCrafterBuild': {'hi': True, 'hl': True, 'oi': 'dep'},
    'HeatProducer': {'hi': True, 'hl': True, 'oi': 'dep', 'rot': True},
    'HeatProducerBuild': {'hi': True, 'hl': True, 'oi': 'dep', 'rot': True},
    'HeaterGenerator': {'hl': True, 'oi': False, 'ol': True, 'rot': True},
    'HeaterGeneratorBuild': {'hl': True, 'oi': False, 'ol': True, 'rot': True},
    'HugAI': {'rot': True},
    'ImpactReactor': {'hi': True, 'hl': True, 'oi': False},
    'ImpactReactorBuild': {'hi': True, 'hl': True, 'oi': False},
    'Incinerator': {'hl': True},
    'IncineratorBuild': {'hl': True},
    'ItemBridge': {'hi': True},
    'ItemBridgeBuild': {'hi': True},
    'ItemEntry': {'hi': True, 'oi': False, 'rot': True},
    'ItemSource': {'hi': True, 'oi': True},
    'ItemSourceBuild': {'hi': True, 'oi': True},
    'ItemTurret': {'hi': True, 'oi': False, 'rot': True},
    'ItemTurretBuild': {'hi': True, 'oi': False, 'rot': True},
    'Junction': {'oi': True},
    'JunctionBuild': {'oi': True},
    'LandingPad': {'hi': True, 'hl': True, 'oi': True},
    'LandingPadBuild': {'hi': True, 'hl': True, 'oi': True},
    'LaserTurret': {'oi': False, 'rot': True},
    'LaserTurretBuild': {'oi': False, 'rot': True},
    'LaunchPad': {'hi': True, 'oi': False},
    'LaunchPadBuild': {'hi': True, 'oi': False},
    'LaunchPayloadComp': {'hi': True, 'oi': False},
    'LegacyUnitFactory': {'hi': True},
    'LegacyUnitFactoryBuild': {'hi': True},
    'LiquidBlock': {'hl': True, 'ol': True},
    'LiquidBridge': {'hl': True, 'ol': True},
    'LiquidBridgeBuild': {'hl': True, 'ol': True},
    'LiquidBuild': {'hl': True, 'ol': True},
    'LiquidJunction': {'hl': True, 'ol': True},
    'LiquidRouter': {'hl': True, 'ol': True},
    'LiquidRouterBuild': {'hl': True, 'ol': True},
    'LiquidSource': {'hl': True, 'ol': True},
    'LiquidSourceBuild': {'hl': True, 'ol': True},
    'LiquidTurret': {'hl': True, 'oi': False, 'rot': True},
    'LiquidTurretBuild': {'hl': True, 'oi': False, 'rot': True},
    'LiquidVoid': {'hl': True},
    'LiquidVoidBuild': {'hl': True},
    'LogicAI': {'rot': True},
    'LogicFx': {'rot': True},
    'MassDriver': {'hi': True},
    'MassDriverBuild': {'hi': True},
    'MendBuild': {'hi': True, 'oi': False},
    'MendProjector': {'hi': True, 'oi': False},
    'MineWeapon': {'rot': True},
    'MinerAI': {'rot': True},
    'MissileAI': {'rot': True},
    'NuclearReactor': {'hi': True, 'hl': True, 'oi': False},
    'NuclearReactorBuild': {'hi': True, 'hl': True, 'oi': False},
    'OverdriveBuild': {'hi': True, 'oi': False},
    'OverdriveProjector': {'hi': True, 'oi': False},
    'OverflowDuct': {'hi': True, 'rot': True},
    'OverflowDuctBuild': {'hi': True, 'rot': True},
    'OverflowGate': {'hi': True, 'oi': True},
    'OverflowGateBuild': {'hi': True, 'oi': True},
    'PayloadAmmoTurret': {'oi': False, 'rot': True},
    'PayloadConveyor': {'rot': True},
    'PayloadConveyorBuild': {'rot': True},
    'PayloadDeconstructor': {'hi': True},
    'PayloadDeconstructorBuild': {'hi': True},
    'PayloadDriverBuild': {'rot': True},
    'PayloadLoader': {'hi': True, 'hl': True, 'oi': False, 'rot': True},
    'PayloadLoaderBuild': {'hi': True, 'hl': True, 'oi': False, 'rot': True},
    'PayloadMassDriver': {'rot': True},
    'PayloadMassDriverData': {'rot': True},
    'PayloadRouter': {'rot': True},
    'PayloadRouterBuild': {'rot': True},
    'PayloadSource': {'rot': True},
    'PayloadSourceBuild': {'rot': True},
    'PayloadTurretBuild': {'oi': False, 'rot': True},
    'PayloadUnloader': {'hi': True, 'hl': True, 'oi': True, 'ol': True, 'rot': True},
    'PayloadUnloaderBuild': {'hi': True, 'hl': True, 'oi': True, 'ol': True, 'rot': True},
    'PointDefenseBulletWeapon': {'rot': True},
    'PointDefenseWeapon': {'rot': True},
    'PowerDiode': {'rot': True},
    'PowerDiodeBuild': {'rot': True},
    'PowerGenerator': {'oi': False},
    'PowerTurret': {'oi': False, 'rot': True},
    'PowerTurretBuild': {'oi': False, 'rot': True},
    'PrebuildAI': {'rot': True},
    'Pump': {'hl': True, 'ol': True},
    'PumpBuild': {'hl': True, 'ol': True},
    'Reconstructor': {'rot': True},
    'ReconstructorBuild': {'rot': True},
    'RegenProjector': {'hi': True, 'oi': False},
    'RegenProjectorBuild': {'hi': True, 'oi': False},
    'RepairAI': {'rot': True},
    'RepairBeamWeapon': {'rot': True},
    'RepairPointBuild': {'hl': True},
    'RepairTurret': {'hl': True},
    'Router': {'hi': True},
    'RouterBuild': {'hi': True},
    'Separator': {'hi': True, 'hl': True},
    'SeparatorBuild': {'hi': True, 'hl': True},
    'SingleBlockProducer': {'hi': True, 'rot': True},
    'SingleBlockProducerBuild': {'hi': True, 'rot': True},
    'SolarGenerator': {'oi': False},
    'SolarGeneratorBuild': {'oi': False},
    'SolidPump': {'hl': True, 'oi': False, 'ol': True},
    'SolidPumpBuild': {'hl': True, 'oi': False, 'ol': True},
    'Sorter': {'oi': True},
    'SorterBuild': {'oi': True},
    'StackConveyor': {'hi': True, 'rot': True},
    'StackConveyorBuild': {'hi': True, 'rot': True},
    'StackRouter': {'hi': True, 'rot': True},
    'StackRouterBuild': {'hi': True, 'rot': True},
    'StorageBlock': {'hi': True, 'oi': False},
    'StorageBuild': {'hi': True, 'oi': False},
    'SuicideAI': {'rot': True},
    'ThermalGenerator': {'hl': True, 'oi': False, 'ol': True},
    'ThermalGeneratorBuild': {'hl': True, 'oi': False, 'ol': True},
    'Thruster': {'rot': True},
    'ThrusterBuild': {'rot': True},
    'Turret': {'oi': False, 'rot': True},
    'TurretBuild': {'oi': False, 'rot': True},
    'UnitAssembler': {'hi': True, 'rot': True},
    'UnitAssemblerBuild': {'hi': True, 'rot': True},
    'UnitAssemblerModule': {'rot': True},
    'UnitAssemblerModuleBuild': {'rot': True},
    'UnitBlock': {'rot': True},
    'UnitBuild': {'rot': True},
    'UnitCargoLoader': {'hi': True, 'oi': False},
    'UnitCargoUnloadPoint': {'hi': True},
    'UnitCargoUnloadPointBuild': {'hi': True},
    'UnitFactory': {'hi': True, 'oi': False, 'rot': True},
    'UnitFactoryBuild': {'hi': True, 'oi': False, 'rot': True},
    'UnitPlan': {'hi': True, 'oi': False, 'rot': True},
    'UnitTransportSourceBuild': {'hi': True, 'oi': False},
    'Unloader': {'hi': True},
    'UnloaderBuild': {'hi': True},
    'VariableReactor': {'oi': False},
    'VariableReactorBuild': {'oi': False},
    'WallCrafter': {'hi': True, 'oi': True, 'rot': True},
    'WallCrafterBuild': {'hi': True, 'oi': True, 'rot': True},
    'YeetData': {'hi': True, 'rot': True},
}
